FROM golang:1.22 AS builder

ENV GOPROXY=https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.org

WORKDIR /build

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY cmd/main.go .

RUN go build -v -o ./main ./main.go

###########START NEW IMAGE###################
FROM builder AS production

LABEL Author="George Leonard (georgelza@gmail.com)"

WORKDIR /app

COPY --from=builder /build/main .

CMD ["/app/main"]
